#!/bin/bash

pick_aliases() {
  pushd "$(dirname "${BASH_SOURCE[0]}")/../../aliases" &> /dev/null

  # This is so the $bundle_option_list separates were it should
  oIFS=$IFS

  # This avoids filling a description for each item using a invisible space char here        🡓
  local aliases_files=($(ls *.sh|sed 's#.sh##'|awk '{a[$1]=$1}END{for(i in a)printf " "a[i]"   on "}'))
  local aliases_dir=$(pwd)
  local aliases_to_be_sourced=""

  exec 3>&1;
  local selected_aliases=$(dialog --keep-tite --title 'MOTD' \
      --checklist 'Pick which sets of aliases should be enabled:' 20 60 16\
      ${aliases_files[@]} \
      2>&1 1>&3 \
  )
  exec 3>&-

  # Out of aliases folder
  popd &>/dev/null

  IFS=" "

  if [ -z "${selected_aliases[@]}" ]; then
    log WARN "No aliases selected."
    return
  fi

  # shellcheck disable=SC2068
  for filename in ${selected_aliases[@]}; do
    aliases_to_be_sourced="${aliases_to_be_sourced}source \"${aliases_dir}/${filename}.sh\"
"
  done
  IFS=$oIFS

  cat <<EOF >"$HOME/.bash_aliases"
#!/bin/bash

# DO NOT EDIT THIS FILE DIRECTLY!
# This file has been generated automatically by the dotfiles setup script.
# Edit the corresponding aliases in the dotfiles directory, or create a
# file named .bash_aliases.local in your home with custom aliases.

$aliases_to_be_sourced
EOF
}

