name: Verify

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1

  bats:
    name: Bats
    runs-on: ubuntu-latest
    needs:
      - shellcheck
    container:
      image: bats/bats:latest
      volumes:
        - $GITHUB_WORKSPACE:/dotfiles
    steps:
    - uses: actions/checkout@v1
    - name: BATS
      uses: docker://bats/bats:latest
      with:
        args: --tap /dotfiles/test
